from eq import eq
from buttons import *


def events(root, entry):
	root.bind_all("<KP_0>", lambda e: zero(entry))
	root.bind_all("<KP_1>", lambda e: one(entry))
	root.bind_all("<KP_2>", lambda e: two(entry))
	root.bind_all("<KP_3>", lambda e: three(entry))
	root.bind_all("<KP_4>", lambda e: four(entry))
	root.bind_all("<KP_5>", lambda e: five(entry))
	root.bind_all("<KP_6>", lambda e: six(entry))
	root.bind_all("<KP_7>", lambda e: seven(entry))
	root.bind_all("<KP_8>", lambda e: eight(entry))
	root.bind_all("<KP_9>", lambda e: nine(entry))
	root.bind_all("<KP_Decimal>", lambda e: dot(entry))
	root.bind_all("<period>", lambda e: dot(entry))
	root.bind_all("<KP_Enter>", lambda e: eq(entry))
	root.bind_all("<Return>", lambda e: eq(entry))
	root.bind_all("<equal>", lambda e: eq(entry))
	root.bind_all("<KP_Add>", lambda e: add(entry))
	root.bind_all("<plus>", lambda e: add(entry))
	root.bind_all("<KP_Subtract>", lambda e: sub(entry))
	root.bind_all("<minus>", lambda e: sub(entry))
	root.bind_all("<KP_Multiply>", lambda e: mul(entry))
	root.bind_all("<asterisk>", lambda e: mul(entry))
	root.bind_all("<KP_Divide>", lambda e: div(entry))
	root.bind_all("<slash>", lambda e: div(entry))
	root.bind_all("<KP_Equal>", lambda e: eq(entry))
	root.bind_all("<BackSpace>", lambda e: delete(entry))
	root.bind_all("<BackSpace>", lambda e: delete(entry))
	root.bind_all("<parenleft>", lambda e: open_bracket(entry))
	root.bind_all("<parenright>", lambda e: close_bracket(entry))
	root.bind_all("<percent>", lambda e: mod(entry))
	root.focus_set()
